version: "3.8"
services:
  proxy:
    image: traefik:v2.9.6
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    expose:
      - 80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  front:
    image: jairum/front-mineria
    ports:
      - "3009:3009"
    environment:
      - BACKEND=http://proxy/app1
    labels:
      - "traefik.http.routers.front.rule=PathPrefix(`/app2`)"
      - "traefik.http.middlewares.front.stripprefix.prefixes=/app2"
      - "traefik.http.routers.front.middlewares=front"
      - "traefik.http.services.front.loadbalancer.server.port=3009"
    expose:
      - 3009
